In [60]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/logistic-regression/titanic/train.csv
/kaggle/input/logistic-regression/titanic/test.csv
/kaggle/input/logistic-regression/titanic/gender_submission.csv
/kaggle/input/logistic-regression/train.csv/train.csv
/kaggle/input/logistic-regression/test.csv/test.csv


In [61]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [62]:
x_train=pd.read_csv("/kaggle/input/logistic-regression/titanic/train.csv")

In [63]:
x_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [64]:
x_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [65]:
l1=['PassengerId','Name','Ticket']

In [66]:
x_train.drop(l1,axis=1,inplace=True)

In [67]:
x_train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [68]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    object 
 8   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(3)
memory usage: 62.8+ KB


In [69]:
l2=['Cabin']
x_train.drop(l2,axis=1,inplace=True)
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    object 
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
dtypes: float64(2), int64(4), object(2)
memory usage: 55.8+ KB


In [70]:
x_train.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Embarked      2
dtype: int64

In [71]:

x_train["Age"].fillna(x_train["Age"].mean(),inplace=True)

      
      

In [72]:
x_train.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    2
dtype: int64

In [73]:
type(x_train["Embarked"].mode())

pandas.core.series.Series

In [74]:
x_train.shape

(891, 8)

In [75]:
x_train.head()

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [76]:
from sklearn.preprocessing import LabelEncoder
le_g=LabelEncoder()
le_e=LabelEncoder()

In [77]:
x_train["Sex"]=le_g.fit_transform(x_train["Sex"])
x_train["Embarked"]=le_e.fit_transform(x_train["Embarked"])


In [78]:
x_train.head()

Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [79]:
x=x_train.iloc[:,1:].values
y=x_train.iloc[:,0].values
x.shape,y.shape

((891, 7), (891,))

In [80]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

In [81]:
x[:5]

array([[ 0.82737724,  0.73769513, -0.5924806 ,  0.43279337, -0.47367361,
        -0.50244517,  0.58111394],
       [-1.56610693, -1.35557354,  0.63878901,  0.43279337, -0.47367361,
         0.78684529, -1.93846038],
       [ 0.82737724, -1.35557354, -0.2846632 , -0.4745452 , -0.47367361,
        -0.48885426,  0.58111394],
       [-1.56610693, -1.35557354,  0.40792596,  0.43279337, -0.47367361,
         0.42073024,  0.58111394],
       [ 0.82737724,  0.73769513,  0.40792596, -0.4745452 , -0.47367361,
        -0.48633742,  0.58111394]])

In [82]:
from sklearn.linear_model import LogisticRegression

In [83]:
clf=LogisticRegression(solver='sag',n_jobs=-1)

In [84]:
clf.fit(x,y)

LogisticRegression(n_jobs=-1, solver='sag')

In [85]:
y_pred=clf.predict(x)

In [86]:
clf.score(x,y)

0.8013468013468014

In [87]:
from sklearn.metrics import confusion_matrix

In [88]:
print(confusion_matrix(y_pred,y))

[[474 102]
 [ 75 240]]


SVM

In [89]:
from sklearn.svm import SVC

In [113]:
clf1=SVC(C=100,gamma=1,decision_function_shape='ovo')

In [114]:
clf1.fit(x,y)

SVC(C=100, decision_function_shape='ovo', gamma=1)

In [115]:
pred_y1=clf1.predict(x)

In [116]:
clf1.score(x,y)

0.9135802469135802

In [117]:
print(confusion_matrix(pred_y1,y))

[[517  45]
 [ 32 297]]


In [119]:
pred_y1=pd.DataFrame(pred_y1)

In [121]:
pred_y1.to_csv("answer")